In [23]:
import numpy as np

test_board = np.zeros((3,3))
test_board[1,1] = 1
test_board[0,2] = 2


In [27]:
smallboards = np.zeros((9,3,3))
bigboard = np.zeros((3,3))

maxdepth = 3


def checkwin(board):
    if(3 in np.sum(board,axis = 0) or 3 in np.sum(board,axis = 1)):
        return True
    
    if board[1,1]:
        if board[0,0] and board[2,2]:
            return True
        if board[0,2] and board[2,0]:
            return True
    
    return False


def checkwinner(board):
    for i in range(1,3):
        if checkwin(board == i):
            return i
    return 0
    
    
def get_other_turn(turn):
    if(turn == 1):
        return 2
    return 1
    

    
# def minimax(board, turn, depth = 0, score = 0):
#     if depth > maxdepth:
#         return score   
    
#     win = checkwinner(board)
#     if win == 0:
#         return score
#     elif win == player:
#         score += 10
#     else:
#         score -= 10
        
#     for p in zip(np.where(board == 0)):
#         tb = board.copy()
#         tb[p] = turn
#         return minimax(tb,other_turn(turn),depth + 1,score)
    

    
def minimax(board,turn,player,score = 0):

    for p in zip(np.where(board == 0)):
        tb = board.copy()
        tb[p] = turn
        
        win = checkwinner(board)
        if win == 0:
            score += minimax(tb,get_other_turn(turn),player,score)
        elif win == player:
            score += 10
        else:
            score -= 10
    
    return score

In [41]:
def choose_action(_board,player):
    board = _board.copy()
    maxscore = -9999
    best_move = None
    for p in zip(np.where(board == 0)):
        score = minimax(board,player,player)
        print(score)
        if score > maxscore:
            score = maxscore
            best_move = p
    
    if best_move != None:
        print("asdasdasa",best_move)
        bb = _board.copy()
        bb[p] = player
        return bb
    else:
        return "AASSSHSHH"

In [42]:
print(test_board,"\n\n", choose_action(test_board,1))

60
60
asdasdasa (array([0, 1, 0, 2, 0, 1, 2], dtype=int64),)
[[0. 0. 2.]
 [0. 1. 0.]
 [0. 0. 0.]] 

 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
